os: linux
dist: trusty

# sudo: false instructs Travis to build our project in a docker VM (faster)
sudo: required

# language: instructs travis what compilers && environment to set up in build matrix
language: java

# Travis CI clones repositories to a depth of 50 commits
git:
  depth: 3

# to test against multiple JDKs 
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    recipients:
      # travis encrypt "ci@example.org" --add notifications.email.recipients
      secure: a46xNyzDxp0Pn1MuIzps2mJs3dS4zR+5t86k8QqjkKJmptVO2zvEXOHtVvekkLgsk3bveAlglJfHyw/eDeBu45rOlAPf6eW+/WqdnGsndsxZlC4gVZWoriBEyeLMGnFxw61CpauY3p8hOH/JHo89Is+oMnQZ1+fIpHQsLblkpmUFCGNOnniKN1iFu2JL/9xqgbQCNMBJ8ZujP9ZofAfDS/WCleyK4HWV8BVM2oU6PPV/WZ5lqeVxZ1vOLb+R3WYi90wJKJs3VlsyEIw25KxIxMEEGbIFcB+bTbpJqjhmHzNQcg0stbKQM6mHSXbIm9qGNzyCCU+4V5VZ12+iL+Lxi/MhNBxOfZ1zKDwCDxX1wxYYHYGGhRijJBvqk58y492/BJN8oIgY5acacv8ov7jcVD7EWAms9oY+yhMHwoQ2pP4hc9u8wq2FcCpDietTt1YYC3aQL1kaJXRPtoyJW/JEJ4TxBgXjrZjHniSrESSUysVrz+F7xY+Hzid8jG6oWY70rkt09v+rSWYY1eHJ0cVMcIhQxW1WlR132DBg5AJ5qEsO+C1bZqqYwB/llzE3hS8UAmxdYjESTncF0Ryieu/lL5Tb8vdsd54fj2tkU0lKInXGD7Ka0gz5mpXdbF0g34iPHcD68qWbQ06U6Hf9Hk9CBYzan4b+FjBYQBLNoDEaeMc=
    on_success: change
    on_failure: always
  slack:
    secure: R/NOIQPMOck41uie9B64j7NWsEypC9MEj1gfO8uJeNiEo/HKQ2bEAtDwfV158riu3ysOJIMLRnuqJ1fk2FI/yoct50vXV6v9KVaEJYARl/HMnXMLfiZ76twv0ozWzH8r/SnOYEDo7wDmrWXI7A2FxcFhpkHCWiKMg0K10aPBSEvcxx4kyFBqzFT/7zFY6ZebF10XoqyaKcDCwr79OoEAYpGaSCz2nbWmZVLExehJrDjubkia2PIo7iPFixe/AeREhJ/KH7l9FNCC/STS58IkByE7Tw0Wc+9LkPHZjvrsku3G7En8pt1aWQRqHrHrnpUGr7o6zlJsjitzaN8eHdMRvF2WnCTLyDK3SetTOkeXL5k1mNaDCMfjTN6G5Uf+eF7Ggo70P3I2SRwJ8h0Z5Qpnt9LLa2et/IMfApzop1kYv5xranrwPYhiLjCo8A1YhHsL4528Quj9Ra/Zblsxt4hei/HVBqNXEkE6+W8aDeGAx3YVhv3L2UAKD/9lQChFE4FP5Gux59XX+0cD/FuLDmH0BH3QZZOdNG8XiPpFuS+XmU2ORNTuv99gE4Jp0To7ytjgcMFV0B/etnFIopfy8A9t7qmOPIzpG1HGEF5r1biBSNFLPIx+Q09/P0bzsyhS3y1VJ4CvDyJQXGFj1SoweH3Ky5ua1Eh8Sw2ft3L4eHyaFY8=

# overwrite the default build step
script: ant
